SISFORM_WEB/Controllers/CartaController.cs
using Microsoft.Azure;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using SISFORM_WEB.ServicioWcf;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SISFORM_WEB.Controllers
{
    public class CartaController : Controller
    {
        // GET: Carta
        public ActionResult CartaPreocupacion()
        {
            return View();
        }

        public PartialViewResult _CartaPreocupacionPV()
        {
            return PartialView();
        }
        public async Task<string> ListarIncidenciasAbiertasPorECMCsv(int ID_Empresa)
        {
            try
            {
                string rpta = "";
                ServicioClient servicio = new ServicioClient("BasicHttpBinding_IServicio");
                rpta = await servicio.ListarIncidenciasAbiertasPorECMCsvAsync(ID_Empresa);
                return rpta;
            }
            catch (Exception ex)
            {
                throw;
            }
        }
        public async Task<string> ObenerterCorrelativoCartaECMCsv(int ID_Empresa)
        {
            try
            {
                string rpta = "";
                ServicioClient servicio = new ServicioClient("BasicHttpBinding_IServicio");
                rpta = await servicio.ObenerterCorrelativoCartaECMCsvAsync(ID_Empresa);
                return rpta;
            }
            catch (Exception ex)
            {
                throw;
            }
        }
        public async Task<string> ListarCartasPreocupacionCsv()
        {
            try
            {
                string rpta = "";
                ServicioClient servicio = new ServicioClient("BasicHttpBinding_IServicio");
                rpta = await servicio.ListarCartasPreocupacionCsvAsync();
                return rpta;
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        public class datosCartaPresentacion
        {
            public string dataPDF { get; set; }
            public int FK_ID_EmpresaECM { get; set; }
            public string fechaCarta { get; set; }
            public int correlativoCarta { get; set; }
            public int usuario { get; set; }
        }
        public async Task<int> GrabarCarta(datosCartaPresentacion odatosCartaPresentacion)
        {
            try
            {
                /*Para convertir la Vista Parcial en PDF
                var viewAsPdf = new ViewAsPdf("_CartaPreocupacionPV", "hola")
                {
                    FileName = "pruebaNombre.pdf",
                    //PageSize = Size.A4,
                    PageMargins = { Left = 1, Right = 1 }
                };
                var pdfBytes = viewAsPdf.BuildFile(ControllerContext);
                */
                byte[] pdfBytes = Convert.FromBase64String(odatosCartaPresentacion.dataPDF);
                String keys = CloudConfigurationManager.GetSetting("ConexionStoreAzure");
                CloudStorageAccount storageAccount = CloudStorageAccount.Parse(keys);
                CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();
                CloudBlobContainer container = blobClient.GetContainerReference("storecartas");
                CloudBlockBlob blockBlob = container.GetBlockBlobReference(odatosCartaPresentacion.FK_ID_EmpresaECM +"-"+ odatosCartaPresentacion.fechaCarta+"-"+ odatosCartaPresentacion.correlativoCarta+".pdf");
                blockBlob.UploadFromByteArray(pdfBytes, 0, pdfBytes.Length);

                CartaPreocupacion ocartaPreocupacion = new CartaPreocupacion();
                ocartaPreocupacion.FK_ID_EmpresaECM = odatosCartaPresentacion.FK_ID_EmpresaECM;
                ocartaPreocupacion.fechaCarta= odatosCartaPresentacion.fechaCarta;
                ocartaPreocupacion.correlativoCarta = odatosCartaPresentacion.correlativoCarta;
                ocartaPreocupacion.FK_ID_UsuarioCrea = odatosCartaPresentacion.usuario;
                //var attachment = new Attachment(new MemoryStream(pdfBytes), "pruebaNombre.pdf");
                //email.Attachments.Add(attachment);
                int rpta;
                ServicioClient servicio = new ServicioClient("BasicHttpBinding_IServicio");
                rpta = await servicio.CartaPreocupacionOperacionAsync(ocartaPreocupacion, "I");
                return rpta;
            }
            catch (Exception ex)
            {
                throw;
            }
        }
    }
}

SISFORM_WEB/Views/Carta/CartaPreocupacion.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section modals{
    <script>
        var siteActive = document.getElementById("docs-section-id");
        siteActive.value = "CartaPreocupacion";
    </script>
}
<div class="content">
    <div class="title"><h5>Carta Preocupación</h5></div>
    <div class="form-row">
        <div class="col-sm-4">
            <label for="txtbuscarPorEmpresa" class="required">Nombre la ECM</label>
            <input type="text" class="form-control form-control-sm E" id="txtbuscarPorEmpresa" placeholder="Nombre Empresa" required="required" />
        </div>
    </div>
    <div class="form-row">
        <div class="col-sm-3">
            <label for="txtFechaInspeccion">Fecha de Carta de Preocupacion</label>
            <input type="date" class="form-control form-control-sm E" id="txtFechaCarta" required="required" />
        </div>
    </div>
    <div class="form-row" id="listadoIncidencias" style="display:none">
        <div class="col-sm-9 text-center">
            <div class="text-right">
                <label>N° de Incidencias: </label>
                <label id="lblNumeroIncidencias"></label>
            </div>
            <fieldset>
                <legend>Listado de Incidencias</legend>
                <table class="table" id="tablaIncidencias">
                    <thead id="IncidenciasEmpresa">
                    </thead>
                    <tbody id="IncidenciasDeLaEmpresa">
                    </tbody>
                </table>
            </fieldset>
        </div>
    </div>
    <div class="form-row">
        <div class="col-sm-4">
            @*<a href="#verificarCarta-modal" class="btn btn-secondary" id="btnVerificarCarta" role="button">Verificar Carta</a>*@
            <a id="btnVerificarCarta" href="@Url.Action("_CartaPreocupacionPV", "Carta")"
               class="btn btn-secondary" role="button"
                <span class="name">Vizualizar Carta</span>
            </a>
            <button class="btn btn-primary" type="button" id="bntNuevo">Nuevo</button>
        </div>
    </div>
</div>

<div class="content">
    <hr class="mb-20" />
</div>
<div class="mw-full">
    <div class="card p-0 bg-very-dark-dm">
        <div id="divTabla" class="table-responsive">
            <table id="tablaDatos" class="table table-inner-bordered">
            </table>
        </div>
    </div>
</div>
<iframe name="print_frame" width="0" height="0" frameborder="0" src="about:blank"></iframe>
@section scripts{
    @Scripts.Render("~/Scripts/ConsultaCartaPreocupacion.js")
}

SISFORM_WEB/Views/Carta/_CartaPreocupacionPV.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <link href="~/Styles/cartaPreocupacion.css" rel="stylesheet">
    <link href="~/Styles/normalize.css" rel="stylesheet">

</head>
<body>
    <div class="totalCarta" id="totaldelaCarta">
        <div class="derecha" align="left">
            <img src="~/Content/Logo-MINSUR.jpg" alt="Logo de Minsur" width="160" height="80" />
            <p> Lima, <span id="fechaCarta"></span></p>
        </div>
        <div class="data">
            <div>
                <p><span id="soloAño"></span>-<span id="soloMes"></span>-GUM-JC-0001</p>
            </div>
            <p>Señores</p>
            <b><p id="nombreECM"></p></b>
            <p>Atencion: &nbsp;&nbsp;&nbsp;&nbsp;Sr.&nbsp;&nbsp;<span id="encargadoECM"></span></p>
            <p>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span>Cargo Representate</span>
            </p>Asunto:  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span>Carta de preocupación por la falta de cumplimiento de Protocolos COVID-19 y requisitos de Salud y Seguridad en el trabajo</span> </p>
            <br />
            <p>Estimado Señor:</p>
            <p align="justify">
                Mediante la presente, nos dirigimos a usted para expresarle nuestra profunda preocupación en relación con la falta de cumplimiento de los protocolos COVID 19 y requisitos de Salud y Seguridad en el trabajo.
            </p>
            <p align="justify">A la fecha tenemos <span id="cantidadIncidenciastexto"></span> observaciones abiertas (anexo), las cuales se necesita levantar a la brevedad posible, es necesario enviar un plan de acción para corregir la desviación y las acciones correctivas que permitan prevenir este tipo de observaciones en vuestra empresa.</p>
            <p align="justify">Finalmente, instamos a que tomen las acciones inmediatas para corregir a la brevedad posible lo mencionado líneas arriba, respetando los compromisos, estándares y directivas establecidas para la ejecución de este contrato.</p>
            <br />
            <p>Sin otro particular, quedamos a usted.</p>
            <p>Atentamente.</p>
            <br />
            <br />
        </div>
        <div class="derecha">
            <p> Lima, <span id="fechaCartaFinal"></span></p>
        </div>
        <div>
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
        </div>
        <div class="flexContainer">
            <div class="piePaginaIzquierda">
                <p>Jr. Giovanni Batista Lorenzo Bernini </p>
                <p>Nro 149 Of 501 San Borja Lima Perú </p>
                <br />
                <p>Telf. (511)215-8330</p>
            </div>
            <div class="piePaginaDerecha">
                <p>Inscrita en la P.E. Nro 01141929 del</p>
                <p>registro de Personas Jurídicas de Lima </p>
            </div>
        </div>
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <button class="btn btn-success" type="button" id="bntGrabarCarta">Grabar Carta</button>
        <div class="listadoIncidenciasEmpresa" id="listadoIncidencias" style="display:none">
            <div>
                <div class="text-right">
                    <label>N° de Incidencias: </label>
                    <label id="lblNumeroIncidencias"></label>
                </div>
                <fieldset>
                    <legend>Listado de Incidencias</legend>
                    <table class="table" id="tablaIncidencias">
                        <thead id="IncidenciasEmpresa">
                        </thead>
                        <tbody id="IncidenciasDeLaEmpresa">
                        </tbody>
                    </table>
                </fieldset>
            </div>
        </div>
    </div>
    <script src="~/plugins/html2pdf/html2pdf.js"></script>
    <script src="~/Scripts/Cosulta_VPCartaPre.js"></script>
</body>
</html>